blank_issues_enabled: false
contact_links:
  - name: Other
    url: https://github.com/melikechan/degoogle/discussions
    about: >
      Alternatifler ile ilgili olmayan herhangi bir sorunuz mu var?
      "Discussions" sekmesini kullanabilirsiniz.
