name: Build
on:
  push:
    branches:
      - main
      - tr-translation
    paths: # Only build if these files were modified
      - src/yaml/*.yml
      - src/md/*.md
      - src/_build.js
      - src/_wiki.js
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # GH_PAT must be a PAT for repo owner
        token: ${{ secrets.GH_PAT }}
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Build README
      run: npm i && node src/_build.js
    - name: Commit & Push
      # GH_NAME/GH_EMAIL can be any collaborator account with Force Push access
      run: |
        git add README.md
        git config --local user.name "${{ vars.GH_NAME }}"
        git config --local user.email "${{ vars.GH_EMAIL }}"
        git commit --allow-empty -m "Generated README.md"
        git push --force-with-lease
